# This Dockerfile is used to build an headles vnc image based on Ubuntu

FROM ubuntu:16.04
MAINTAINER Tobias Schneck "tobias.schneck@consol.de"
ENV REFRESHED_AT 2018-03-27

LABEL io.k8s.description="Headless VNC Container with Xfce window manager, firefox and chromium" \
      io.k8s.display-name="Headless VNC Container based on Ubuntu" \
      io.openshift.expose-services="6901:http,5901:xvnc" \
      io.openshift.tags="vnc, ubuntu, xfce" \
      io.openshift.non-scalable=true
RUN apt-get update -y 
RUN apt-get install -y ssh
RUN apt-get clean -y
EXPOSE 22
CMD ["/etc/init.d/ssh","start"]
