# This Dockerfile is used to build an headles vnc image based on Ubuntu

FROM ubuntu:16.04
RUN apt-get update -y 
RUN apt-get install -y vim wget net-tools locales gedit xrdp ssh
RUN apt-get clean -y
CMD ["--wait"]
