# This Dockerfile is used to build an headles vnc image based on Ubuntu

FROM ubuntu:16.04
RUN apt-get update -y 
RUN apt-get install -y ssh
RUN apt-get clean -y
EXPOSE 22
USER 0
CMD ["/etc/init.d/ssh","start"]
